<?php

class Sparo_CharityProcessor_Model_States {
  public function toOptionArray(){
    return array(
      array('value' => '', 'label' => 'Select'),
      array('value' => 'AL', 'label' => 'AL'),
    	array('value' => 'AK', 'label' => 'AK'),
    	array('value' => 'AZ', 'label' => 'AZ'),
    	array('value' => 'AR', 'label' => 'AR'),
    	array('value' => 'CA', 'label' => 'CA'),
    	array('value' => 'CO', 'label' => 'CO'),
    	array('value' => 'CT', 'label' => 'CT'),
    	array('value' => 'DE', 'label' => 'DE'),
    	array('value' => 'DC', 'label' => 'DC'),
    	array('value' => 'FL', 'label' => 'FL'),
    	array('value' => 'GA', 'label' => 'GA'),
    	array('value' => 'HI', 'label' => 'HI'),
    	array('value' => 'ID', 'label' => 'ID'),
    	array('value' => 'IL', 'label' => 'IL'),
    	array('value' => 'IN', 'label' => 'IN'),
    	array('value' => 'IA', 'label' => 'IA'),
    	array('value' => 'KS', 'label' => 'KS'),
    	array('value' => 'KY', 'label' => 'KY'),
    	array('value' => 'LA', 'label' => 'LA'),
    	array('value' => 'ME', 'label' => 'ME'),
    	array('value' => 'MD', 'label' => 'MD'),
    	array('value' => 'MA', 'label' => 'MA'),
    	array('value' => 'MI', 'label' => 'MI'),
    	array('value' => 'MN', 'label' => 'MN'),
    	array('value' => 'MS', 'label' => 'MS'),
    	array('value' => 'MO', 'label' => 'MO'),
    	array('value' => 'MT', 'label' => 'MT'),
    	array('value' => 'NE', 'label' => 'NE'),
    	array('value' => 'NV', 'label' => 'NV'),
    	array('value' => 'NH', 'label' => 'NH'),
    	array('value' => 'NJ', 'label' => 'NJ'),
    	array('value' => 'NM', 'label' => 'NM'),
    	array('value' => 'NY', 'label' => 'NY'),
    	array('value' => 'NC', 'label' => 'NC'),
    	array('value' => 'ND', 'label' => 'ND'),
    	array('value' => 'OH', 'label' => 'OH'),
    	array('value' => 'OK', 'label' => 'OK'),
    	array('value' => 'OR', 'label' => 'OR'),
    	array('value' => 'PA', 'label' => 'PA'),
    	array('value' => 'RI', 'label' => 'RI'),
    	array('value' => 'SC', 'label' => 'SC'),
    	array('value' => 'SD', 'label' => 'SD'),
    	array('value' => 'TN', 'label' => 'TN'),
    	array('value' => 'TX', 'label' => 'TX'),
    	array('value' => 'UT', 'label' => 'UT'),
    	array('value' => 'VT', 'label' => 'VT'),
    	array('value' => 'VA', 'label' => 'VA'),
    	array('value' => 'WA', 'label' => 'WA'),
    	array('value' => 'WV', 'label' => 'WV'),
    	array('value' => 'WI', 'label' => 'WI'),
    	array('value' => 'WY', 'label' => 'WY')
    );
  }
}
